server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          default-label: circuit-breaker
          uri: https://github.com/DevPrivateCMPH/microservices_sb
          search-paths: config-data
  application:
    name: config-service